spring:
  application:
    name: libraryapi
  config:
    import: optional:file:./.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: ${SERVER_PORT:8000}

scalar:
  enabled: true
  path: /scalar
  url: /v3/api-docs
  page-title: Library API

security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER:library-api}
    access-expiration: ${JWT_ACCESS_EXPIRATION:15m}
  refresh-token:
    expiration: ${REFRESH_TOKEN_EXPIRATION:7d}
